import { useEffect, useState } from 'react';
import QRCode from 'qrcode';
import { authClient } from './supabase.js';
import LoginPage from './LoginPage.jsx';

const initialProducts = [
  { id: 1, name: 'Sunflower Oil 1L', sku: 'OIL-101', category: 'Oils', rate: 145, mrp: 165, stock: 3, minimum: 10 },
  { id: 2, name: 'Premium Tea 500g', sku: 'TEA-204', category: 'Beverages', rate: 230, mrp: 260, stock: 8, minimum: 10 },
  { id: 3, name: 'Toor Dal 1kg', sku: 'DAL-308', category: 'Pulses', rate: 120, mrp: 145, stock: 36, minimum: 12 },
  { id: 4, name: 'Fortune Rice 5kg', sku: 'RIC-412', category: 'Rice', rate: 355, mrp: 390, stock: 2, minimum: 8 },
];
const initialCustomers = [
  { id: 1, name: 'Shree Krishna Stores', contact: 'Suresh Shah', mobile: '98765 22110', city: 'Ulhasnagar', outstanding: 32500 },
  { id: 2, name: 'Mahavir Agencies', contact: 'Mahesh Jain', mobile: '98210 88420', city: 'Kalyan', outstanding: 24180 },
  { id: 3, name: 'Sai Mart', contact: 'Prakash More', mobile: '97631 44678', city: 'Ambernath', outstanding: 0 },
];

function DashboardApp({ user, onSignOut }) {
  const [page, setPage] = useState('Home');
  const [products, setProducts] = useState(initialProducts);
  const [customers, setCustomers] = useState(initialCustomers);
  const [orders, setOrders] = useState([]);
  const [toast, setToast] = useState('');
  const flash = (message) => { setToast(message); window.setTimeout(() => setToast(''), 2600); };
  const navigate = (next) => setPage(next);
  const lowStock = products.filter((p) => p.stock <= p.minimum).length;
  const content = { Home: <Home lowStock={lowStock} go={navigate} />, Products: <Products products={products} setProducts={setProducts} flash={flash} />, Inventory: <Inventory products={products} setProducts={setProducts} flash={flash} />, Customers: <Customers customers={customers} setCustomers={setCustomers} flash={flash} />, 'Delivery Orders': <DeliveryOrders products={products} customers={customers} orders={orders} setOrders={setOrders} setProducts={setProducts} flash={flash} /> }[page];
  return <div className="app"><aside><div className="brand"><span>G</span><div><strong>Gurukripa</strong><small>TRADING</small></div></div><nav>{['Home', 'Delivery Orders', 'Products', 'Inventory', 'Customers'].map((item) => <button className={page === item ? 'active' : ''} onClick={() => navigate(item)} key={item}><i>{icons[item]}</i>{item}</button>)}</nav><div className="business"><b>GURUKRIPA TRADING</b><small>Ulhasnagar-5</small></div></aside><main><header><div className="crumb">Business Desk <span>/</span> {page}</div><button className="user" title={`Sign out ${user?.email || ''}`} onClick={onSignOut}>{user?.email?.slice(0, 2).toUpperCase() || 'AS'}</button></header><section className="content">{content}</section></main>{toast && <div className="toast">✓ {toast}</div>}</div>;
}

function App() {
  const [session, setSession] = useState(() => authClient.getSession());
  const signOut = () => { authClient.signOut(); setSession(null); };
  if (!session) return <LoginPage onLogin={setSession}/>;
  return <DashboardApp user={session.user} onSignOut={signOut}/>;
}
const icons = { Home: '▦', 'Delivery Orders': '▱', Products: '□', Inventory: '◫', Customers: '♙' };

function Home({ lowStock, go }) { return <><div className="intro"><div><p>GURUKRIPA TRADING</p><h1>Good morning, <span>Admin.</span></h1><small>Manage your daily billing and delivery operations from one place.</small></div><button className="primary" onClick={() => go('Delivery Orders')}>＋ New Delivery Order</button></div><div className="metrics"><Metric name="Today’s Sales" value="₹48,750" hint="↗ 12.5% vs yesterday"/><Metric name="Delivery Orders" value="08" hint="2 awaiting invoice"/><Metric name="Products" value="04" hint="Active catalog items"/><Metric name="Low Stock" value={String(lowStock).padStart(2, '0')} hint="● Needs attention" alert/></div><section className="card welcome-card"><h2>Quick actions</h2><p>Create and track daily delivery orders, keep product stock up to date, and manage your customer directory.</p><div><button onClick={() => go('Delivery Orders')}>Create delivery order →</button><button onClick={() => go('Products')}>Manage products →</button><button onClick={() => go('Customers')}>View customers →</button></div></section></> }
function Metric({ name, value, hint, alert }) { return <article className="card metric"><small>{name}</small><strong>{value}</strong><p className={alert ? 'alert' : ''}>{hint}</p></article> }

function Products({ products, setProducts, flash }) { const [search, setSearch] = useState(''); const [adding, setAdding] = useState(false); const [form, setForm] = useState({ name: '', sku: '', category: '', rate: '', mrp: '', stock: '', minimum: '' }); const visible = products.filter((p) => p.name.toLowerCase().includes(search.toLowerCase()) || p.sku.toLowerCase().includes(search.toLowerCase())); const add = (e) => { e.preventDefault(); if (!form.name || !form.sku) return; setProducts([...products, { ...form, id: Date.now(), rate: Number(form.rate || 0), mrp: Number(form.mrp || 0), stock: Number(form.stock || 0), minimum: Number(form.minimum || 0) }]); setAdding(false); setForm({ name: '', sku: '', category: '', rate: '', mrp: '', stock: '', minimum: '' }); flash('Product added to catalog.'); }; return <><PageTitle title="Products" subtitle="Manage your product catalog and selling rates" action="＋ Add product" onAction={() => setAdding(!adding)}/>{adding && <form className="entry-form" onSubmit={add}><Input label="Product name" value={form.name} onChange={(v) => setForm({ ...form, name: v })}/><Input label="SKU / code" value={form.sku} onChange={(v) => setForm({ ...form, sku: v })}/><Input label="Category" value={form.category} onChange={(v) => setForm({ ...form, category: v })}/><Input label="Selling rate" type="number" value={form.rate} onChange={(v) => setForm({ ...form, rate: v })}/><Input label="MRP" type="number" value={form.mrp} onChange={(v) => setForm({ ...form, mrp: v })}/><Input label="Opening stock" type="number" value={form.stock} onChange={(v) => setForm({ ...form, stock: v })}/><Input label="Minimum stock" type="number" value={form.minimum} onChange={(v) => setForm({ ...form, minimum: v })}/><button className="primary">Save product</button></form>}<div className="toolbar"><input placeholder="Search by product or SKU..." value={search} onChange={(e) => setSearch(e.target.value)}/><span>{products.length} products</span></div><ProductTable products={visible}/></> }
function ProductTable({ products }) { return <div className="card table-wrap"><table><thead><tr><th>PRODUCT</th><th>SKU</th><th>CATEGORY</th><th>SELLING RATE</th><th>MRP</th><th>CURRENT STOCK</th><th>STATUS</th></tr></thead><tbody>{products.map((p) => <tr key={p.id}><td><b>{p.name}</b></td><td>{p.sku}</td><td>{p.category || '—'}</td><td>₹{p.rate}</td><td>₹{p.mrp || 0}</td><td><b>{p.stock} units</b></td><td><mark className={p.stock <= p.minimum ? 'low' : 'available'}>{p.stock <= p.minimum ? 'Low stock' : 'Available'}</mark></td></tr>)}</tbody></table></div> }

function Inventory({ products, setProducts, flash }) { const [productId, setProductId] = useState(products[0]?.id || ''); const [quantity, setQuantity] = useState(''); const stockIn = () => { const qty = Number(quantity); if (!qty || qty < 1) return; setProducts(products.map((p) => p.id === Number(productId) ? { ...p, stock: p.stock + qty } : p)); setQuantity(''); flash(`${qty} units added to inventory.`); }; return <><PageTitle title="Inventory" subtitle="Check stock levels and record stock received"/><div className="inventory-grid"><section className="card adjust"><h2>Add stock</h2><p>Every update is kept against the product inventory record.</p><label>Product<select value={productId} onChange={(e) => setProductId(e.target.value)}>{products.map((p) => <option value={p.id} key={p.id}>{p.name}</option>)}</select></label><label>Quantity received<input type="number" min="1" value={quantity} onChange={(e) => setQuantity(e.target.value)} placeholder="Enter quantity"/></label><button className="primary" onClick={stockIn}>Add to inventory</button></section><section className="card inventory-note"><b>Inventory rule</b><p>Confirmed delivery orders deduct stock automatically. Stock cannot go below zero.</p></section></div><ProductTable products={products}/></> }

function Customers({ customers, setCustomers, flash }) { const [adding, setAdding] = useState(false); const [form, setForm] = useState({ name: '', contact: '', mobile: '', city: '' }); const add = (e) => { e.preventDefault(); if (!form.name) return; setCustomers([...customers, { ...form, id: Date.now(), outstanding: 0 }]); setAdding(false); setForm({ name: '', contact: '', mobile: '', city: '' }); flash('Customer added successfully.'); }; return <><PageTitle title="Customers" subtitle="Your party and customer directory" action="＋ Add customer" onAction={() => setAdding(!adding)}/>{adding && <form className="entry-form four" onSubmit={add}><Input label="Party name" value={form.name} onChange={(v) => setForm({ ...form, name: v })}/><Input label="Contact person" value={form.contact} onChange={(v) => setForm({ ...form, contact: v })}/><Input label="Mobile number" value={form.mobile} onChange={(v) => setForm({ ...form, mobile: v })}/><Input label="City" value={form.city} onChange={(v) => setForm({ ...form, city: v })}/><button className="primary">Save customer</button></form>}<div className="card table-wrap"><table><thead><tr><th>PARTY NAME</th><th>CONTACT PERSON</th><th>MOBILE</th><th>CITY</th><th>OUTSTANDING</th></tr></thead><tbody>{customers.map((c) => <tr key={c.id}><td><b>{c.name}</b></td><td>{c.contact || '—'}</td><td>{c.mobile || '—'}</td><td>{c.city || '—'}</td><td><b>₹{c.outstanding.toLocaleString('en-IN')}</b></td></tr>)}</tbody></table></div></> }

function DeliveryOrders({ products, customers, orders, setOrders, setProducts, flash }) {
  const emptyLine = () => ({ productId: String(products[0]?.id || ''), quantity: 1 });
  const [customerId, setCustomerId] = useState(String(customers[0]?.id || ''));
  const [lines, setLines] = useState([emptyLine()]);
  const [printOrder, setPrintOrder] = useState(null);
  const updateLine = (index, key, value) => setLines(lines.map((line, i) => i === index ? { ...line, [key]: value } : line));
  const total = lines.reduce((sum, line) => sum + (products.find((p) => p.id === Number(line.productId))?.rate || 0) * (Number(line.quantity) || 0), 0);
  const submit = (e) => { e.preventDefault(); const customer = customers.find((c) => c.id === Number(customerId)); const items = lines.map((line) => { const product = products.find((p) => p.id === Number(line.productId)); return product && { productId: product.id, product: product.name, rate: product.rate, mrp: product.mrp || 0, quantity: Number(line.quantity), amount: product.rate * Number(line.quantity) }; }).filter(Boolean); if (!customer || !items.length || items.some((item) => !item.quantity)) return flash('Add at least one product and quantity.'); const required = items.reduce((map, item) => ({ ...map, [item.productId]: (map[item.productId] || 0) + item.quantity }), {}); const insufficient = products.find((p) => required[p.id] > p.stock); if (insufficient) return flash(`Only ${insufficient.stock} units of ${insufficient.name} are available.`); const number = `DO-${String(orders.length + 1).padStart(5, '0')}`; const order = { number, customer: customer.name, customerAddress: `${customer.city || 'Ulhasnagar'}, Maharashtra`, customerMobile: customer.mobile || '—', items, amount: total, date: new Date().toLocaleDateString('en-IN', { day: '2-digit', month: 'short', year: 'numeric' }) }; setOrders([order, ...orders]); setProducts(products.map((p) => required[p.id] ? { ...p, stock: p.stock - required[p.id] } : p)); setPrintOrder(order); setLines([emptyLine()]); flash(`${number} confirmed. Inventory updated.`); };
  return <><PageTitle title="Delivery Orders" subtitle="Create an order and reduce inventory on confirmation"/><div className="order-grid no-print"><form className="card order-form" onSubmit={submit}><h2>New delivery order</h2><label>Customer<select value={customerId} onChange={(e) => setCustomerId(e.target.value)}>{customers.map((c) => <option key={c.id} value={c.id}>{c.name}</option>)}</select></label><div className="line-head"><b>Product lines</b><button type="button" className="add-line" onClick={() => setLines([...lines, emptyLine()])}>＋ Add line</button></div>{lines.map((line, index) => <div className="order-line" key={index}><select value={line.productId} onChange={(e) => updateLine(index, 'productId', e.target.value)}>{products.map((p) => <option key={p.id} value={p.id}>{p.name} — ₹{p.rate}</option>)}</select><input aria-label="Quantity" type="number" min="1" value={line.quantity} onChange={(e) => updateLine(index, 'quantity', e.target.value)}/><b>₹{((products.find((p) => p.id === Number(line.productId))?.rate || 0) * (Number(line.quantity) || 0)).toLocaleString('en-IN')}</b>{lines.length > 1 && <button type="button" className="remove-line" onClick={() => setLines(lines.filter((_, i) => i !== index))}>×</button>}</div>)}<div className="order-total"><span>Order value</span><b>₹{total.toLocaleString('en-IN')}</b></div><button className="primary">Confirm delivery</button><small>Confirmation records a stock-out movement for this order.</small></form><section className="card process"><h2>Delivery workflow</h2><ol><li>Select customer</li><li>Add one or more products</li><li>Confirm delivery order</li><li>Print the delivery challan</li></ol></section></div><div className="card table-wrap no-print"><div className="table-heading"><h2>Recent delivery orders</h2><small>{orders.length ? `${orders.length} confirmed orders` : 'No delivery orders confirmed yet'}</small></div>{orders.length > 0 && <table><thead><tr><th>ORDER NO.</th><th>CUSTOMER</th><th>ITEMS</th><th>AMOUNT</th><th>STATUS</th><th></th></tr></thead><tbody>{orders.map((o) => <tr key={o.number}><td><b>{o.number}</b></td><td>{o.customer}</td><td>{o.items.map((item) => `${item.product} × ${item.quantity}`).join(', ')}</td><td>₹{o.amount.toLocaleString('en-IN')}</td><td><mark className="available">Delivered</mark></td><td><button className="print-button" onClick={() => setPrintOrder(o)}>Print</button></td></tr>)}</tbody></table>}</div>{printOrder && <Challan order={printOrder} onClose={() => setPrintOrder(null)}/>}</>;
}
function UpiQr() { const [source, setSource] = useState(''); useEffect(() => { QRCode.toDataURL('upi://pay?pa=9623079356%40okbizaxis&pn=GURUKRIPA%20TRADING&cu=INR', { errorCorrectionLevel: 'H', margin: 1, width: 360 }).then(setSource); const taxBox = document.querySelector('.tax-box'); if (taxBox) { const amount = taxBox.querySelector('strong:last-child')?.textContent || ''; taxBox.dataset.taxable = amount; taxBox.closest('.challan-summary')?.setAttribute('data-taxable', amount); } }, []); return source ? <img src={source} alt="UPI QR for Gurukripa Trading"/> : <span>Generating UPI QR…</span>; }
function Challan({ order, onClose }) { return <div className="challan-modal"><div className="challan-actions no-print"><button className="outline" onClick={onClose}>Close preview</button><button className="primary" onClick={() => window.print()}>🖨 Print delivery order</button></div><article className="challan"><header><div><h1>GURUKRIPA TRADING</h1><p>SHOP NO. 1, SATYA SAI MAHAL, GANDHI ROAD, ULHASNAGAR - 5 • MOB. 9623079356</p></div><div><p><b>GST NO. 27AARPV4965I2Z</b></p><p><b>FSSAI : 21526022003603</b></p></div></header><h2>DELIVERY ORDER</h2><section className="challan-party"><div><b>PARTY NAME :</b> {order.customer}<br/><b>ADDRESS :</b> {order.customerAddress}<br/><b>GST NO. :</b><br/><b>FSSAI NO.</b></div><div><b>SR. NO.</b> {order.number}<br/><b>DATE :</b> {order.date}<br/><b>SALESMAN :</b></div></section><table><thead><tr><th>SR.</th><th>DESCRIPTION</th><th>MRP</th><th>RATE</th><th>QTY</th><th>AMOUNT</th></tr></thead><tbody>{order.items.map((item, index) => <tr key={item.productId}><td>{index + 1}</td><td>{item.product}</td><td>₹{item.mrp}</td><td>₹{item.rate}</td><td>{item.quantity}</td><td>₹{item.amount.toLocaleString('en-IN')}</td></tr>)}{Array.from({ length: Math.max(0, 15 - order.items.length) }).map((_, index) => <tr key={`empty-${index}`}><td>{order.items.length + index + 1}</td><td></td><td></td><td></td><td></td><td></td></tr>)}</tbody></table><section className="challan-summary"><div className="declaration"><p>SUBJECT TO ULHASNAGAR JURISDICTION</p><span>*I/We hereby certify that the foods/food mentioned in this invoice is/are warranted to be of the nature and quality which it/these purport/ purports to be. Certified that the particulars given above are true and correct. E. &amp; O.E.</span></div><div className="tax-box"><b>TAX AMOUNT :</b><span></span><b>ADD :</b><span></span><b>CGST :</b><span></span><b>SGST :</b><span></span><strong>TOTAL AMOUNT :</strong><strong>₹{order.amount.toLocaleString('en-IN')}</strong></div></section><section className="payment-details"><div><h3>Bank Details</h3><p><b>Union Bank of India</b><br/>Account Name: GURUKRIPA TRADING<br/>Account Number: 681901010050590<br/>IFSC Code: UBIN0568198<br/>Branch: NETAJI CHOWK - ULHASNAGAR</p></div><div className="qr"><UpiQr/><span>Scan &amp; pay via UPI</span></div><div className="signature"><b>For Guru Kripa Trading</b><span>Authorised Signatory</span></div></section><div className="advertisement-space"><span>ADVERTISEMENT SPACE</span></div></article></div> }
function PageTitle({ title, subtitle, action, onAction }) { return <div className="page-title"><div><h1>{title}</h1><p>{subtitle}</p></div>{action && <button className="primary" onClick={onAction}>{action}</button>}</div> }
function Input({ label, type = 'text', value, onChange }) { return <label>{label}<input type={type} value={value} onChange={(e) => onChange(e.target.value)}/></label> }
export default App;
