import { StrictMode } from 'react';
import { createRoot } from 'react-dom/client';
import './styles.css';
import './auth.css';
import './print.css';
import './order-lines.css';
import './payment-details.css';
import './tax-linear.css';
import './tax-layout.css';
import './tax-final.css';
import './tax-duplicate.css';
import './tax-structure.css';
import './tax-horizontal.css';
import './tax-polish.css';
import './tax-refine.css';
import './print-borders.css';
import './tax-border-uniform.css';
import './taxable-table.css';
import './taxable-polish.css';
import App from './App.jsx';
createRoot(document.getElementById('root')).render(<StrictMode><App /></StrictMode>);
